name = "Dezcraft"
author = "Bamsy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77442aebce345fa3f27517b015822e66c0f85444f9b14ed9a0108e339a246047"

[versions]
forge = "47.2.1"
minecraft = "1.20.1"
