name = "Merpcraft 1"
author = "Bamsy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87b73074abf997d9d8a7df1d32f5e10a5b1cb7a55386f54e8b052672f70bc28b"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
