name = "Merpcraft 1"
author = "Bamsy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e65c4fb4ce60410eae9fb9e413de50850e0713f94322f9b787f2cec59a4a22c8"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
