name = "Merpcraft"
author = "Bamsy"
version = "1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "903e719ca7aaaead291fa892073403cfe19a17638184c09ac5886d794dcfbb6d"

[versions]
forge = "47.2.1"
minecraft = "1.20.1"

[options]
datapack-folder = "/config/paxi/datapacks"
