name = "Merpcraft 1"
author = "Bamsy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4d4e819a2bf4cd3a49c9c5a58c661c475a14fbddae968880bff07cd61c636b6"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
