name = "Merpcraft"
author = "Bamsy"
version = "1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4762d181026b942e98f287d0766eff277476e4fcae28eb0cc584a2ffb6f3316"

[versions]
forge = "47.2.1"
minecraft = "1.20.1"

[options]
datapack-folder = "/config/paxi/datapacks"
