name = "Merpcraft"
author = "Bamsy"
version = "1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "287e2662e132065856026a38d934bf1d05590dd5e4227422ba7737b0ee2215d4"

[versions]
forge = "47.2.1"
minecraft = "1.20.1"
