name = "Merpcraft 1"
author = "Bamsy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa6e2eb2a2c66a15efbe709c0270886eb20a002415e375ef62bd76e6f9b596f2"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
