name = "Merpcraft 1"
author = "Bamsy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42f247953fb0f54c1941b8e887dab05fc43e6f4af3cb558daa98cfa0a428a43f"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
