name = "Merpcraft"
author = "Bamsy"
version = "1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0de32e155e95614e087264b374c26985a3ef643acbad3ac8f29eb8aea2e4fc62"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"

[options]
datapack-folder = "/config/paxi/datapacks"
