name = "Merpcraft 1"
author = "Bamsy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "162ce21941ed480c873f25d224942fab4ad6ee20ad4c13d0aa34b5e7463ed5eb"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
