name = "Merpcraft"
author = "Bamsy"
version = "1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd43c5ce2a98b7f7749dfdc0901dc82f2842439bcb1acbafbe5148d470339a3a"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"

[options]
datapack-folder = "/config/paxi/datapacks"
