name = "Merpcraft 1"
author = "Bamsy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b05678c0eeada94ae44a58d533235b686e12d9ef778419b82bd8461570d2645e"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
